# Install anaconda Python stack and some other useful tools
FROM quay.io/jupyter/base-notebook

USER root
RUN apt-get update && \
  apt-get install -y dialog net-tools build-essential libopenmpi-dev libblis-serial-dev liblapack-dev git cmake curl less make pkgconf python3-scipy libnetcdf-dev libnetcdff-dev python3-cartopy python3-pyproj rasterio bash-completion nano vim
USER jovyan

# Install PETSc

ENV PETSC_DIR=${HOME}/petsc
ENV PETSC_ARCH=ompi-int32-real-opt
WORKDIR ${HOME}
RUN git clone --depth=1 --branch release https://gitlab.com/petsc/petsc.git
RUN cd ${PETSC_DIR} && \
    OPT='-O3 -march=haswell -ffp-contract=fast' && \
    python3 configure \
        --with-debugging=0 COPTFLAGS="$OPT" CXXOPTFLAGS="$OPT" FOPTFLAGS="$OPT" && \
    make
ENV LD_LIBRARY_PATH=${PETSC_DIR}/${PETSC_ARCH}/lib

# set env variables
ENV CLAW=${HOME}/clawpack-v5-12-0
ENV FC=gfortran

# Install clawpack-v5.12.0 (into $HOME/clawpack-v5-12-0):

RUN git clone https://github.com/clawpack/clawpack.git ${CLAW}
WORKDIR ${CLAW}
RUN git checkout v5.12.0
RUN git submodule init
RUN git submodule update
RUN pip install -r requirements-dev.txt

RUN pip install --no-build-isolation -e ./

# set prompt:
RUN echo 'export PS1="jovyan $ "' >> ~/.bashrc

# Clone the apps repository (with master checked out):
RUN git clone https://github.com/clawpack/apps.git

WORKDIR ${HOME}

# fix a few things for git:
RUN git config --file .gitconfig core.pager more
RUN git config --file .gitconfig core.editor vim

# Add packages needed for the book http://www.clawpack.org/riemann_book/
# REMOVED

CMD [ "/bin/bash" ]
